### ISSUE TITLE
Re-implementing in PHP

### ISSUE THREAD

**Issue by willemstuursma** [stephen304/castblock#15]
Hi, 

I am running castblock on my Raspberry Pi B which works nicely.

I noticed various issues such as high CPU usage that could be solved with a proper (non looping) re-implementation in a higher level programming language.

I have the skills to create such an implementation in PHP. However, I don't have muck skills in docker or linux tooling. 

I was wondering if you would take a PR for such an implementation. If so, I will set aside some time to create one.

**Comment by stephen304** [comment]
Hi @willemstuursma, I've actually been meaning to use go to re-implement some of the core functionality to solve this. Unfortunately, I have to focus on interviews at the moment, so I can't really commit much time to this right now.

The main reason I was planning on using go is because go-chromecast is in go, so it might be easier to extend that codebase or use parts of it.

Another option would be to augment the current script with a long-lived go binary to replace some of the processes that get repeatedly spawned.

At any rate, you're welcome to fork or reimplement parts if you want, I may just not have time to review this for a while.

**Comment by willemstuursma** [comment]
Hi @stephen304. Thank you for your swift reply and setting expectations.

Unfortunately go is not in my skillset, but I try to make a nice PHP implementation then. I'll open a PR here when I get to it. 

Good luck with your interviews.

**Comment by willemstuursma** [comment]
Hi @stephen304. I have made some progress [here](https://github.com/willemstuursma/castblock-php).

I am aiming to create only the PHP part and a `.phar` build (this is a single file containing the PHP code and all dependencies which can be ran by the `php` interpreter). This `phar` file could replace `bin/castblock` file in your repository, if you so please. It solves most of the limitations listed.

**Comment by willemstuursma** [comment]
Hi @stephen304. I've finished the .phar replacement for this library. Maybe you can include this or point others to that library, as it solves most of the issues in this project.
