### ISSUE TITLE
Docker support?

### ISSUE THREAD

**Issue by SerinitySW** [stephen304/castblock#6]
This project seems absolutely amazing, love what you've created here. Would be fantastic to have an official docker image to pull!

**Comment by stephen304** [comment]
Thanks :) It shouldn't be too hard to make a dockerfile, the only thing that could get in the way is if the docker networking prevents discovery of the chromecast. But maybe it will just work. I'll give it a shot when I get a chance

**Comment by stephen304** [comment]
So I got this far, and it builds a container that can run, but I think my suspicions about the networking prevent it from detecting anything:

```
FROM golang:buster

WORKDIR /opt/castblock
COPY . .

RUN go get -u github.com/vishen/go-chromecast

RUN apt-get update && apt-get install -y jq bc diffutils coreutils bsdmainutils

CMD ["/opt/castblock/castblock"]
```

The workings of the chromecast protocol are a mystery to me which is why I offloaded it to go-chromecast. I'm guessing go-chromecast detects chromecasts using some sort of broadcast-based discovery protocol. If you have any ideas how to get it to work I'm all ears, otherwise I'll revisit this.

**Comment by stephen304** [comment]
Actually I figured it out, or at least a workaround. If you run the resulting container with `docker run --network="host" <containerid>` then it seems to work as expected.

**Comment by stephen304** [comment]
@SerinitySW Let me know if that helps, I'm not too familiar with using docker

**Comment by stephen304** [comment]
I updated the docker image with a multi stage build which really cut down on the image size. I would love to get multi arch support in but I'm not sure atm how to add it in the most elegant way

**Comment by stephen304** [comment]
Closing this as a dockerfile is available
