### ISSUE TITLE
Syntax error: "(" unexpected

### ISSUE THREAD

**Issue by Bluscream** [stephen304/castblock#8]
```
blu@netguard:~/castblock/castblock-master $ sh /usr/bin/castblock
/usr/bin/castblock: 10: /usr/bin/castblock: Syntax error: "(" unexpected
```

**Comment by stephen304** [comment]
You can also use the docker container if you don't want to install bash

**Comment by Bluscream** [comment]
sadly docker did not work for me because it doesn't seem to contain ARM executables

**Comment by stephen304** [comment]
Gotcha, the only reason I haven't created an arm image is because I don't docker well / how to build all arches without doing each one individually. You should be able to run `docker build .` in the project folder on arm and it *should* spit out an arm image. The base images I use work on pretty much all arches.

Most of the dependencies can be installed via your package manager (apt install jq bc, etc). The only exception is go-chromecast unless you're on arch linux (idk if anyone has created packages for other distros)

**Comment by Bluscream** [comment]
i'll try apt soon. Only tried "go get *" until now

**Comment by stephen304** [comment]
You should only have to use go get to install go-chromecast. Everything else is non-golang. I didn't document the apt package names because the package names vary from distro to distro.

**Comment by Bluscream** [comment]
It worked <3
